"use client";

import { useEffect, useState, useRef } from "react";
import { motion } from "framer-motion";
import { useAppStore } from "@/lib/store";
import { ACUITY_LEVELS } from "@/lib/constants";

export default function ResultsScreen() {
    const testResult = useAppStore((s) => s.testResult);
    const setScreen = useAppStore((s) => s.setScreen);
    const resetTest = useAppStore((s) => s.resetTest);
    const resultsRef = useRef<HTMLDivElement>(null);

    const [animatedLogMAR, setAnimatedLogMAR] = useState(1.0);
    const [showConfetti, setShowConfetti] = useState(false);

    useEffect(() => {
        if (!testResult) return;

        // Animate LogMAR counter
        const target = testResult.fractionalLogMAR;
        const duration = 1500;
        const start = Date.now();
        const startVal = 1.0;

        const tick = () => {
            const elapsed = Date.now() - start;
            const progress = Math.min(1, elapsed / duration);
            // Ease out cubic
            const eased = 1 - Math.pow(1 - progress, 3);
            setAnimatedLogMAR(startVal + (target - startVal) * eased);

            if (progress < 1) {
                requestAnimationFrame(tick);
            }
        };
        requestAnimationFrame(tick);

        // Trigger confetti if 20/20 or better
        if (target <= 0) {
            setTimeout(() => setShowConfetti(true), 1800);
        }
    }, [testResult]);

    if (!testResult) {
        return (
            <div className="flex min-h-screen items-center justify-center">
                <p className="text-text-secondary">No test results available.</p>
            </div>
        );
    }

    const durationMin = Math.floor(testResult.testDuration / 60000);
    const durationSec = Math.floor((testResult.testDuration % 60000) / 1000);

    // Star rating based on acuity
    const getStars = (logMAR: number) => {
        if (logMAR <= -0.1) return 5;
        if (logMAR <= 0.0) return 5;
        if (logMAR <= 0.1) return 4;
        if (logMAR <= 0.3) return 3;
        if (logMAR <= 0.5) return 2;
        return 1;
    };
    const stars = getStars(testResult.acuityLogMAR);

    const handleTestAgain = () => {
        resetTest();
        setScreen("camera-setup");
    };

    const handleDownloadPDF = async () => {
        try {
            const { default: jsPDF } = await import("jspdf");
            const doc = new jsPDF();

            doc.setFontSize(24);
            doc.setTextColor(0, 100, 80);
            doc.text("NadiVision — Visual Acuity Report", 20, 25);

            doc.setFontSize(12);
            doc.setTextColor(60, 60, 60);
            doc.text(`Date: ${new Date(testResult.date).toLocaleDateString()}`, 20, 40);
            doc.text(`Test Distance: ${testResult.testDistance.toFixed(2)} m`, 20, 48);
            doc.text(
                `Duration: ${durationMin}m ${durationSec}s`,
                20,
                56
            );

            doc.setFontSize(18);
            doc.setTextColor(0, 0, 0);
            doc.text(`Visual Acuity: ${testResult.acuitySnellen}`, 20, 75);
            doc.text(`LogMAR: ${testResult.fractionalLogMAR.toFixed(2)} (fractional, letter-by-letter)`, 20, 85);
            doc.text(`95% CI: ${testResult.confidenceInterval.lower.toFixed(2)} – ${testResult.confidenceInterval.upper.toFixed(2)} LogMAR`, 20, 93);

            doc.setFontSize(14);
            doc.text("Per-Line Results:", 20, 105);

            let y = 115;
            doc.setFontSize(11);
            for (const score of testResult.perLevelScores) {
                doc.text(
                    `${score.level.snellen}  —  ${score.correct}/${score.total} correct`,
                    25,
                    y
                );
                y += 8;
            }

            doc.setFontSize(9);
            doc.setTextColor(150, 150, 150);
            doc.text("Generated by NadiVision — Camera-based visual acuity testing", 20, 280);

            doc.save(`NadiVision_Report_${new Date().toISOString().split("T")[0]}.pdf`);
        } catch (err) {
            console.error("PDF generation failed:", err);
        }
    };

    return (
        <div className="flex min-h-screen flex-col items-center justify-center px-6 py-12">
            {/* Confetti */}
            {showConfetti && <ConfettiEffect />}

            <motion.div
                ref={resultsRef}
                className="max-w-lg w-full flex flex-col items-center"
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
            >
                {/* Header */}
                <motion.div
                    className="text-center mb-8"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.3 }}
                >
                    <motion.div
                        className="text-4xl mb-2"
                        initial={{ scale: 0 }}
                        animate={{ scale: 1 }}
                        transition={{ delay: 0.5, type: "spring", stiffness: 200 }}
                    >
                        ✦
                    </motion.div>
                    <h2 className="text-3xl font-bold mb-1">Test Complete</h2>
                    <p className="text-text-secondary text-sm">
                        Here are your visual acuity results
                    </p>
                </motion.div>

                {/* Main result card */}
                <motion.div
                    className="glass rounded-3xl p-8 w-full mb-8"
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: 0.5, duration: 0.5 }}
                >
                    <div className="text-center mb-6">
                        <p className="text-sm text-text-muted mb-1 uppercase tracking-wide">
                            Your Acuity
                        </p>
                        <motion.p
                            className="text-6xl font-bold text-primary"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            transition={{ delay: 0.8 }}
                        >
                            {testResult.acuitySnellen}
                        </motion.p>
                        <p className="text-lg font-mono text-text-secondary mt-1">
                            LogMAR: {animatedLogMAR.toFixed(2)}
                        </p>
                        <p className="text-xs text-text-muted mt-2 max-w-xs leading-relaxed">
                            95% CI: {testResult.confidenceInterval.lower.toFixed(2)} – {testResult.confidenceInterval.upper.toFixed(2)} LogMAR
                            &nbsp;·&nbsp;± {((testResult.confidenceInterval.upper - testResult.fractionalLogMAR) / 0.1).toFixed(1)} lines
                        </p>
                    </div>

                    {/* Stars */}
                    <motion.div
                        className="flex justify-center gap-1 mb-6"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: 1.2 }}
                    >
                        {Array.from({ length: 5 }).map((_, i) => (
                            <motion.span
                                key={i}
                                className={`text-2xl ${i < stars ? "text-warning" : "text-surface-light"}`}
                                initial={{ scale: 0, rotate: -180 }}
                                animate={{ scale: 1, rotate: 0 }}
                                transition={{ delay: 1.3 + i * 0.1, type: "spring" }}
                            >
                                ★
                            </motion.span>
                        ))}
                    </motion.div>

                    {/* Meta info */}
                    <div className="flex justify-center gap-8 text-sm text-text-secondary">
                        <div className="text-center">
                            <p className="text-text-muted text-xs">Distance</p>
                            <p className="font-mono">{testResult.testDistance.toFixed(2)}m</p>
                        </div>
                        <div className="text-center">
                            <p className="text-text-muted text-xs">Duration</p>
                            <p className="font-mono">{durationMin}m {durationSec}s</p>
                        </div>
                        <div className="text-center">
                            <p className="text-text-muted text-xs">Trials</p>
                            <p className="font-mono">{testResult.responses.length}</p>
                        </div>
                    </div>
                </motion.div>

                {/* Per-line breakdown */}
                <motion.div
                    className="glass rounded-2xl p-6 w-full mb-8"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 1.0 }}
                >
                    <h3 className="text-sm font-medium text-text-muted mb-4 uppercase tracking-wide">
                        Per-line breakdown
                    </h3>
                    <div className="space-y-3">
                        {testResult.perLevelScores.map((score, i) => {
                            const pct = score.total > 0 ? (score.correct / score.total) * 100 : 0;
                            const isbestLine =
                                score.level.snellen === testResult.acuitySnellen;

                            return (
                                <motion.div
                                    key={score.level.snellen}
                                    className="flex items-center gap-3"
                                    initial={{ opacity: 0, x: -20 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: 1.2 + i * 0.1 }}
                                >
                                    <span
                                        className={`text-sm font-mono w-16 ${isbestLine ? "text-primary font-bold" : "text-text-secondary"
                                            }`}
                                    >
                                        {score.level.snellen}
                                    </span>
                                    <div className="flex-1 h-4 bg-surface-light rounded-full overflow-hidden">
                                        <motion.div
                                            className={`h-full rounded-full ${pct >= 60 ? "bg-success" : pct >= 40 ? "bg-warning" : "bg-danger"
                                                }`}
                                            initial={{ width: 0 }}
                                            animate={{ width: `${pct}%` }}
                                            transition={{ delay: 1.4 + i * 0.1, duration: 0.6, ease: "easeOut" }}
                                        />
                                    </div>
                                    <span className="text-sm font-mono text-text-muted w-12 text-right">
                                        {score.correct}/{score.total}
                                    </span>
                                    {isbestLine && (
                                        <span className="text-xs text-primary">←</span>
                                    )}
                                </motion.div>
                            );
                        })}
                    </div>
                </motion.div>

                {/* Test integrity / cheating flags */}
                {(testResult.cheatingFlags?.length ?? 0) > 0 && (
                    <motion.div
                        className="glass rounded-2xl p-5 w-full mb-6 border border-warning/20"
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 1.3 }}
                    >
                        <h3 className="text-sm font-medium text-warning mb-3 uppercase tracking-wide flex items-center gap-2">
                            <span>⚠</span> Test Integrity Alerts
                        </h3>
                        <div className="space-y-1.5">
                            {testResult.cheatingFlags.map((flag, i) => {
                                const labels: Record<string, string> = {
                                    fullscreen_exit: "Exited fullscreen",
                                    tab_switch: "Switched away from tab",
                                    face_lost: "Face left camera view",
                                    multiple_faces: "Multiple faces detected",
                                    fast_answer: "Unusually fast response",
                                    distance_jump: "Sudden distance change",
                                };
                                return (
                                    <div key={i} className="flex items-center justify-between text-xs">
                                        <span className="text-warning/80">{labels[flag.type] ?? flag.type}</span>
                                        <span className="text-text-muted font-mono">
                                            {flag.detail ? `${flag.detail} · ` : ""}{new Date(flag.timestamp).toLocaleTimeString()}
                                        </span>
                                    </div>
                                );
                            })}
                        </div>
                    </motion.div>
                )}

                {/* Action buttons */}
                <motion.div
                    className="flex gap-4"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 1.8 }}
                >
                    <motion.button
                        onClick={handleDownloadPDF}
                        className="px-6 py-3 rounded-xl border border-white/10 text-text-secondary font-medium
                       hover:bg-surface-light transition-colors duration-200 cursor-pointer"
                        whileHover={{ y: -2 }}
                        whileTap={{ scale: 0.97 }}
                    >
                        Download PDF ↓
                    </motion.button>
                    <motion.button
                        onClick={handleTestAgain}
                        className="px-8 py-3 rounded-xl bg-primary text-background font-semibold
                       glow-primary glow-primary-hover transition-all duration-300 cursor-pointer"
                        whileHover={{ y: -2 }}
                        whileTap={{ scale: 0.97 }}
                    >
                        Test Again ↻
                    </motion.button>
                </motion.div>
            </motion.div>
        </div>
    );
}

// Lightweight confetti component
function ConfettiEffect() {
    const canvasRef = useRef<HTMLCanvasElement>(null);

    useEffect(() => {
        const canvas = canvasRef.current;
        if (!canvas) return;

        const ctx = canvas.getContext("2d");
        if (!ctx) return;

        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;

        const colors = ["#00D4AA", "#6366F1", "#F59E0B", "#10B981", "#EF4444"];
        const particles: {
            x: number;
            y: number;
            vx: number;
            vy: number;
            size: number;
            color: string;
            rotation: number;
            rotSpeed: number;
            opacity: number;
        }[] = [];

        for (let i = 0; i < 80; i++) {
            particles.push({
                x: canvas.width / 2 + (Math.random() - 0.5) * 200,
                y: canvas.height / 2,
                vx: (Math.random() - 0.5) * 8,
                vy: -Math.random() * 12 - 4,
                size: Math.random() * 8 + 3,
                color: colors[Math.floor(Math.random() * colors.length)],
                rotation: Math.random() * 360,
                rotSpeed: (Math.random() - 0.5) * 10,
                opacity: 1,
            });
        }

        let frame = 0;
        const maxFrames = 120;

        const animate = () => {
            if (frame >= maxFrames) return;

            ctx.clearRect(0, 0, canvas.width, canvas.height);

            for (const p of particles) {
                p.x += p.vx;
                p.vy += 0.2; // gravity
                p.y += p.vy;
                p.rotation += p.rotSpeed;
                p.opacity = Math.max(0, 1 - frame / maxFrames);

                ctx.save();
                ctx.translate(p.x, p.y);
                ctx.rotate((p.rotation * Math.PI) / 180);
                ctx.globalAlpha = p.opacity;
                ctx.fillStyle = p.color;
                ctx.fillRect(-p.size / 2, -p.size / 2, p.size, p.size * 0.6);
                ctx.restore();
            }

            frame++;
            requestAnimationFrame(animate);
        };

        animate();
    }, []);

    return (
        <canvas
            ref={canvasRef}
            className="fixed inset-0 pointer-events-none z-50"
        />
    );
}
